/**
 * Vercel 构建时写入 static/config.js，将环境变量 API_URL 注入为前端 API 地址。
 * 在 Vercel 项目设置中配置 Environment Variable: API_URL = https://你的Render应用.onrender.com
 */
const fs = require('fs');
const path = require('path');
const apiUrl = (process.env.API_URL || '').replace(/'/g, "\\'");
const content = `// Auto-generated by Vercel build. Do not edit.\nwindow.__API_BASE__ = '${apiUrl}';\n`;
const outPath = path.join(__dirname, '..', 'static', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('Written config.js with API_BASE:', apiUrl || '(same origin)');
